version: '3.0'
services:
  rasa:
    image: michaelzhao21/hollow-knight-chatbot
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: michaelzhao21/hollow-knight-chatbot-actions
    container_name: action_server
    build: .
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    ports:
      - 5055:5055